### Common

server:
  port: 8585
  tomcat:
    max-threads: 4

spring:
  application:
    name: Jwt-Security
  profiles:
    active: dev,mysql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yml"
    enabled: false

logging:
  level:
    root: INFO


---

### Dev profile

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:springSecurity;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true

eureka:
  client:
    enabled: false

logging:
  level:
    com.chumbok: DEBUG
    org.springframework.security: DEBUG


---

### Prod profile

spring:
  profiles: prod
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/studentportalproject2}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4444/eureka/
    refresh:
      enable: true
  instance:
    hostname: localhost


logging:
  level:
    com.chumbok: DEBUG

---

### Integration test profile

spring:
  profiles: it
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:springSecurity;DB_CLOSE_ON_EXIT=TRUE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true


---

### Docker profile

spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:33001/eureka/


---


### MySQL profile

spring:
  profiles: mysql
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/toletproject?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1221}

---

#spring:
#  profiles: mysql
#  datasource:
#    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/toletproject?createDatabaseIfNotExist=true}
#    username: ${DB_USERNAME:aalhabib001}
#    password: ${DB_PASSWORD:12211221}

---

### Debug profile

spring:
  profiles: debug

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

---


### Enable Eureka profile

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4444/eureka/
    refresh:
      enable: true
  instance:
    hostname: localhost
